# Generated by Django 5.0.14 on 2026-06-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDashboardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("dashboard_type", models.CharField(max_length=50)),
                ("layout", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("notification_type", models.CharField(max_length=100)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("push", "Push"), ("sms", "SMS")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("theme", models.CharField(default="light", max_length=50)),
                (
                    "accent_color",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("font_size", models.CharField(blank=True, max_length=10, null=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("profile_visible", models.BooleanField(default=True)),
                ("activity_visible", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserThemePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("primary_color", models.CharField(default="#0d6efd", max_length=20)),
                ("secondary_color", models.CharField(default="#6c757d", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#ffffff", max_length=20),
                ),
                ("surface_color", models.CharField(default="#f8f9fa", max_length=20)),
                ("text_color", models.CharField(default="#212529", max_length=20)),
                ("border_radius", models.CharField(default="8px", max_length=20)),
                (
                    "font_family",
                    models.CharField(default="Inter, sans-serif", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserWidgetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("widget_id", models.CharField(max_length=100)),
                ("settings", models.JSONField(default=dict)),
                ("visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="userdashboardconfig",
            constraint=models.UniqueConstraint(
                fields=("user_id", "dashboard_type"),
                name="unique_user_dashboard_config",
            ),
        ),
        migrations.AddConstraint(
            model_name="usernotificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user_id", "notification_type", "channel"),
                name="unique_user_notification_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpreference",
            constraint=models.UniqueConstraint(
                fields=("user_id",), name="unique_user_preference"
            ),
        ),
        migrations.AddConstraint(
            model_name="userthemepreference",
            constraint=models.UniqueConstraint(
                fields=("user_id",), name="unique_user_theme_preference"
            ),
        ),
        migrations.AddConstraint(
            model_name="userwidgetconfig",
            constraint=models.UniqueConstraint(
                fields=("user_id", "widget_id"), name="unique_user_widget_config"
            ),
        ),
    ]
